language: generic
dist: bionic

addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-pictures
    - texlive-fonts-recommended
    - latex-cjk-all

script:
  - make tags
